substitutions:
  _NAME: git

steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: sh
  args: ["-c", "gcloud functions deploy git --project subiz-version-4 --entry-point git --runtime nodejs8 --trigger-http"]
