substitutions:
  _NAME: git

steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - functions
  - deploy
  - ${_NAME}
  - '--source=https://source.developers.google.com/projects/${PROJECT_ID}/repos/${REPO_NAME}/moveable-aliases/master/paths/'
  - "--trigger-http"
